<a href="https://colab.research.google.com/github/Shubhamk05/python_projects/blob/main/Machine%20learning/KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

In [ ]:
iris = load_iris()

In [ ]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [ ]:
data = pd.DataFrame(iris["data"])
print(data)

       0    1    2    3
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
..   ...  ...  ...  ...
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[150 rows x 4 columns]


In [ ]:
print(iris["target_names"])


['setosa' 'versicolor' 'virginica']


In [ ]:
print(iris["feature_names"])

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [ ]:
x = data
y = iris["target"]

In [ ]:
x_train , x_test , y_train , y_test = train_test_split(x,y, test_size = 0.2)


In [ ]:
model = KNeighborsClassifier(n_neighbors = 3)

In [ ]:
model.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=3)

In [ ]:
x_predict = model.predict(x_train)
x_accuracy = confusion_matrix(x_predict, y_train)
y_predict = model.predict(x_test)
y_accuracy = confusion_matrix(y_predict,y_test)

In [ ]:
print(x_accuracy)
print(y_accuracy)

[[42  0  0]
 [ 0 38  1]
 [ 0  3 36]]
[[ 8  0  0]
 [ 0  9  2]
 [ 0  0 11]]


In [ ]:
print("Correct predict ", accuracy_score(y_test,y_predict))
print("Wrong prediction", (1-accuracy_score(y_test,y_predict)))

Correct predict  0.9333333333333333
Wrong prediction 0.06666666666666665


In [ ]:
print("Correct predict ", accuracy_score(y_train,x_predict))
print("Wrong prediction", (1-accuracy_score(y_train,x_predict)))

Correct predict  0.9666666666666667
Wrong prediction 0.033333333333333326
